# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('valor_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade_minima', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lucro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='retiradas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uso', models.CharField(choices=[('1', 'Proprio'), ('2', 'Venda')], default=1, max_length=1)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
        migrations.AddField(
            model_name='lote',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
    ]
