# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20170818_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='img',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
