# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_adicional_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcreme',
            old_name='casadinho_item',
            new_name='creme_item',
        ),
    ]
