# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20170830_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acai',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande'), ('X', 'GG')], max_length=1),
        ),
    ]
