# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-13 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_auto_20180410_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acai',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande'), ('S', 'GG')], max_length=1),
        ),
    ]
