# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-18 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('pedidos', '0006_auto_20180410_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
    ]
