# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-07 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_auto_20190407_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='pagamento',
            field=models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito'), ('4', 'Comanada antiga')], default=4, max_length=1),
        ),
    ]
