# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-07 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_comanda_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='pagamento',
            field=models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito'), ('4', 'Comanada sem registro')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='tipo',
            field=models.CharField(choices=[('1', 'Local'), ('2', 'Viagem'), ('3', 'Entrega'), ('4', 'Comanada sem registro')], default=4, max_length=1),
        ),
    ]
