# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-10 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20190213_2008'),
        ('pedidos', '0011_auto_20190407_2028'),
    ]

    operations = [
    ]
