# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_auto_20170829_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 30, 14, 18, 44, 757642)),
        ),
    ]
