# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_auto_20170830_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 15, 13, 54, 394511)),
        ),
    ]
