# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 21:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0004_auto_20170905_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 21, 9, 10, 952881)),
        ),
    ]
