# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0005_auto_20170905_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 22, 20, 46, 978270)),
        ),
    ]
