# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0006_auto_20170905_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 10, 22, 8, 44, 673802)),
        ),
    ]
