# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-10 21:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0008_auto_20181029_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 18, 4, 36, 493259)),
        ),
    ]
