# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0009_auto_20190210_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 12, 17, 33, 20, 563734)),
        ),
    ]
