# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-13 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0010_auto_20190212_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 13, 18, 43, 57, 787087)),
        ),
    ]
