# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-14 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0011_auto_20190213_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 19, 18, 25, 724296)),
        ),
    ]
