# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_auto_20190214_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 28, 13, 58, 17, 297139)),
        ),
    ]
