# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-24 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_auto_20190318_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa_geral',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='caixa_geral',
            name='tipo',
            field=models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartao Debito'), ('3', 'Cartao Credito'), ('4', 'Boleto'), ('5', 'Transferencia')], default=1, max_length=1),
        ),
    ]
