# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-04-10 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0012_auto_20190213_2008'),
        ('caixa', '0017_auto_20190323_2113'),
    ]

    operations = [
    ]
